# Generated by Django 4.2.5 on 2023-10-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitch_shift_app', '0002_remove_pitchshiftresult_format_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitchshiftresult',
            name='filename',
            field=models.FilePathField(null=True),
        ),
    ]
