# Generated by Django 4.2.6 on 2023-10-08 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voice_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LowDenoiseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_channels', models.IntegerField()),
                ('output_sr', models.IntegerField()),
                ('file_extension', models.CharField(max_length=10)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('vocal_file', models.FilePathField(path='voice_split/output_files/')),
                ('instrument_file', models.FilePathField(path='voice_split/output_files/')),
                ('voice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='low_denoise_results', to='voice_manager.voice')),
            ],
        ),
        migrations.CreateModel(
            name='HighDenoiseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_channels', models.IntegerField()),
                ('output_sr', models.IntegerField()),
                ('file_extension', models.CharField(max_length=10)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('output_file', models.FilePathField(path='voice_split/output_files/')),
                ('voice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='high_denoise_results', to='voice_manager.voice')),
            ],
        ),
    ]
