# Generated by Django 4.2.4 on 2023-08-23 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('voice_file', models.FileField(upload_to='user_voices/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoiceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('result_voice_file', models.FilePathField()),
                ('voice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offline_speech_recognition.voice')),
            ],
        ),
        migrations.CreateModel(
            name='VoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('detect_time', models.FloatField()),
                ('command_detected', models.CharField(max_length=150)),
                ('voice_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_details', to='offline_speech_recognition.voiceresult')),
            ],
        ),
    ]
