# Generated by Django 4.2.4 on 2023-08-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('channel', models.IntegerField()),
            ],
        ),
    ]
