# Generated by Django 4.2.4 on 2023-10-01 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voice_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PitchShiftResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_rate', models.IntegerField()),
                ('channel', models.IntegerField()),
                ('format_file', models.CharField(max_length=10)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('voice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voice_manager.voice')),
            ],
        ),
    ]
