# Generated by Django 4.2.5 on 2023-10-04 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voice_manager', '0001_initial'),
        ('pitch_shift_recognition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pitchshiftresult',
            name='format_file',
        ),
        migrations.AddField(
            model_name='pitchshiftresult',
            name='file_extension',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pitchshiftresult',
            name='filename',
            field=models.FileField(null=True, upload_to='pitch_shift_voices/'),
        ),
        migrations.AlterField(
            model_name='pitchshiftresult',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitchshiftresult',
            name='voice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitch_shift_results', to='voice_manager.voice'),
        ),
    ]
